## Generated by dust (version 0.15.3) - do not edit
seirv_age_region <- R6::R6Class(
  "dust",
  cloneable = FALSE,

  private = list(
    pars_ = NULL,
    pars_multi_ = NULL,
    index_ = NULL,
    info_ = NULL,
    n_threads_ = NULL,
    n_particles_ = NULL,
    n_particles_each_ = NULL,
    shape_ = NULL,
    ptr_ = NULL,
    gpu_config_ = NULL,
    ode_control_ = NULL,
    methods_ = NULL,
    param_ = list(array_cov1 = list(has_default = FALSE, default_value = NULL, rank = 3, min = -Inf, max = Inf, integer = FALSE),
     array_cov2 = list(has_default = FALSE, default_value = NULL, rank = 3, min = -Inf, max = Inf, integer = FALSE),
     array_new = list(has_default = FALSE, default_value = NULL, rank = 2, min = -Inf, max = Inf, integer = FALSE),
     beta = list(has_default = FALSE, default_value = NULL, rank = 0, min = -Inf, max = Inf, integer = FALSE),
     c = list(has_default = FALSE, default_value = NULL, rank = 0, min = -Inf, max = Inf, integer = FALSE),
     d = list(has_default = FALSE, default_value = NULL, rank = 2, min = -Inf, max = Inf, integer = FALSE),
     Es_init = list(has_default = FALSE, default_value = NULL, rank = 2, min = -Inf, max = Inf, integer = FALSE),
     Ev1_init = list(has_default = FALSE, default_value = NULL, rank = 2, min = -Inf, max = Inf, integer = FALSE),
     Ev2_init = list(has_default = FALSE, default_value = NULL, rank = 2, min = -Inf, max = Inf, integer = FALSE),
     Is_init = list(has_default = FALSE, default_value = NULL, rank = 2, min = -Inf, max = Inf, integer = FALSE),
     Iv1_init = list(has_default = FALSE, default_value = NULL, rank = 2, min = -Inf, max = Inf, integer = FALSE),
     Iv2_init = list(has_default = FALSE, default_value = NULL, rank = 2, min = -Inf, max = Inf, integer = FALSE),
     m = list(has_default = FALSE, default_value = NULL, rank = 2, min = -Inf, max = Inf, integer = FALSE),
     mean_import = list(has_default = FALSE, default_value = NULL, rank = 2, min = -Inf, max = Inf, integer = FALSE),
     recov = list(has_default = FALSE, default_value = NULL, rank = 2, min = -Inf, max = Inf, integer = FALSE),
     S_init = list(has_default = FALSE, default_value = NULL, rank = 2, min = -Inf, max = Inf, integer = FALSE),
     theta = list(has_default = FALSE, default_value = NULL, rank = 0, min = -Inf, max = Inf, integer = FALSE),
     V1_init = list(has_default = FALSE, default_value = NULL, rank = 2, min = -Inf, max = Inf, integer = FALSE),
     V2_init = list(has_default = FALSE, default_value = NULL, rank = 2, min = -Inf, max = Inf, integer = FALSE),
     waning = list(has_default = FALSE, default_value = NULL, rank = 0, min = -Inf, max = Inf, integer = FALSE),
     X_import = list(has_default = FALSE, default_value = NULL, rank = 0, min = -Inf, max = Inf, integer = FALSE),
     Y_import = list(has_default = FALSE, default_value = NULL, rank = 0, min = -Inf, max = Inf, integer = FALSE),
     year_per_age = list(has_default = FALSE, default_value = NULL, rank = 1, min = -Inf, max = Inf, integer = FALSE),
     year_start = list(has_default = FALSE, default_value = NULL, rank = 0, min = -Inf, max = Inf, integer = FALSE),
     alpha = list(has_default = TRUE, default_value = list("/", 1L, 11L), rank = 0, min = -Inf, max = Inf, integer = FALSE),
     b = list(has_default = TRUE, default_value = 0L, rank = 0, min = -Inf, max = Inf, integer = FALSE),
     delta = list(has_default = TRUE, default_value = list("/", 1L, 120L), rank = 0, min = -Inf, max = Inf, integer = FALSE),
     dt = list(has_default = TRUE, default_value = 1L, rank = 0, min = -Inf, max = Inf, integer = FALSE),
     gamma = list(has_default = TRUE, default_value = list("/", 1L, 8L), rank = 0, min = -Inf, max = Inf, integer = FALSE),
     N_age = list(has_default = TRUE, default_value = 2L, rank = 0, min = -Inf, max = Inf, integer = FALSE),
     N_reg = list(has_default = TRUE, default_value = 2L, rank = 0, min = -Inf, max = Inf, integer = FALSE),
     N_time = list(has_default = TRUE, default_value = 2L, rank = 0, min = -Inf, max = Inf, integer = FALSE),
     v_fail = list(has_default = TRUE, default_value = 0.02, rank = 0, min = -Inf, max = Inf, integer = FALSE),
     v_leak = list(has_default = TRUE, default_value = 0L, rank = 0, min = -Inf, max = Inf, integer = FALSE),
     v_sec = list(has_default = TRUE, default_value = 0L, rank = 0, min = -Inf, max = Inf, integer = FALSE),
     vacc = list(has_default = TRUE, default_value = 1L, rank = 0, min = -Inf, max = Inf, integer = FALSE),
     X = list(has_default = TRUE, default_value = 1L, rank = 0, min = -Inf, max = Inf, integer = FALSE),
     Y = list(has_default = TRUE, default_value = 1L, rank = 0, min = -Inf, max = Inf, integer = FALSE)),
    reload_ = NULL
  ),

  public = list(
    initialize = function(pars, time, n_particles, n_threads = 1L,
                          seed = NULL, pars_multi = FALSE,
                          deterministic = FALSE,
                          gpu_config = NULL, ode_control = NULL) {
      if (is.null(gpu_config)) {
        private$methods_ <- list(
           alloc = dust_cpu_seirv_age_region_alloc,
           run = dust_cpu_seirv_age_region_run,
           simulate = dust_cpu_seirv_age_region_simulate,
           run_adjoint = dust_cpu_seirv_age_region_run_adjoint,
           set_index = dust_cpu_seirv_age_region_set_index,
           n_state = dust_cpu_seirv_age_region_n_state,
           update_state = dust_cpu_seirv_age_region_update_state,
           state = dust_cpu_seirv_age_region_state,
           time = dust_cpu_seirv_age_region_time,
           reorder = dust_cpu_seirv_age_region_reorder,
           resample = dust_cpu_seirv_age_region_resample,
           rng_state = dust_cpu_seirv_age_region_rng_state,
           set_rng_state = dust_cpu_seirv_age_region_set_rng_state,
           set_n_threads = dust_cpu_seirv_age_region_set_n_threads,
           set_data = dust_cpu_seirv_age_region_set_data,
           compare_data = dust_cpu_seirv_age_region_compare_data,
           filter = dust_cpu_seirv_age_region_filter,
           set_stochastic_schedule = dust_cpu_seirv_age_region_set_stochastic_schedule,
           ode_statistics = dust_cpu_seirv_age_region_ode_statistics)
      } else {
        private$methods_ <- list(alloc = function(...) {
          stop("GPU support not enabled for this object")
        })
      }
      res <- private$methods_$alloc(pars, pars_multi, time, n_particles,
                        n_threads, seed, deterministic, gpu_config, ode_control)
      private$pars_ <- pars
      private$pars_multi_ <- pars_multi
      private$n_threads_ <- n_threads
      private$ptr_ <- res[[1L]]
      private$info_ <- res[[2L]]
      private$shape_ <- res[[3L]]
      private$gpu_config_ <- res[[4L]]
      private$ode_control_ <- res[[5L]]
      private$n_particles_ <- prod(private$shape_)
      if (pars_multi) {
        private$n_particles_each_ <- private$n_particles_ / length(pars)
      } else {
        private$n_particles_each_ <- private$n_particles_
      }
    },

    name = function() {
      "seirv_age_region"
    },

    param = function() {
      private$param_
    },

    run = function(time_end) {
      m <- private$methods_$run(private$ptr_, time_end)
      rownames(m) <- names(private$index_)
      m
    },

    simulate = function(time_end) {
      m <- private$methods_$simulate(private$ptr_, time_end)
      rownames(m) <- names(private$index_)
      m
    },

    run_adjoint = function() {
      res <- private$methods_$run_adjoint(private$ptr_)
      ## This approach may want to change, because it won't cope well
      ## with cases where are gradient is structured with respect to
      ## some parameters, but perhaps it's still a reasonable thing to
      ## do? While we have array-free models it's fine though.
      nms <- private$info_$adjoint
      if (!is.null(nms) && length(nms) == length(res$gradient)) {
        names(res$gradient) <- nms
      }
      res
    },

    set_index = function(index) {
      private$methods_$set_index(private$ptr_, index)
      private$index_ <- index
      invisible()
    },

    index = function() {
      private$index_
    },

    ode_control = function() {
      private$ode_control_
    },

    ode_statistics = function() {
      private$methods_$ode_statistics(private$ptr_)
    },

    n_threads = function() {
      private$n_threads_
    },

    n_state = function() {
      private$methods_$n_state(private$ptr_)
    },

    n_particles = function() {
      private$n_particles_
    },

    n_particles_each = function() {
      private$n_particles_each_
    },

    shape = function() {
      private$shape_
    },

    update_state = function(pars = NULL, state = NULL, time = NULL,
                            set_initial_state = NULL, index = NULL,
                            reset_step_size = NULL) {
      info <- private$methods_$update_state(private$ptr_, pars, state, time,
                                          set_initial_state, index,
                                          reset_step_size)
      if (!is.null(pars)) {
        private$info_ <- info
        private$pars_ <- pars
      }
      invisible()
    },

    state = function(index = NULL) {
      m <- private$methods_$state(private$ptr_, index)
      rownames(m) <- names(index)
      m
    },

    time = function() {
      private$methods_$time(private$ptr_)
    },

    set_stochastic_schedule = function(time) {
      private$methods_$set_stochastic_schedule(private$ptr_, time)
      invisible()
    },

    reorder = function(index) {
      storage.mode(index) <- "integer"
      private$methods_$reorder(private$ptr_, index)
      invisible()
    },

    resample = function(weights) {
      invisible(private$methods_$resample(private$ptr_, weights))
    },

    info = function() {
      private$info_
    },

    pars = function() {
      private$pars_
    },

    rng_state = function(first_only = FALSE, last_only = FALSE) {
      private$methods_$rng_state(private$ptr_, first_only, last_only)
    },

    set_rng_state = function(rng_state) {
      private$methods_$set_rng_state(private$ptr_, rng_state)
      invisible()
    },

    has_openmp = function() {
      dust_cpu_seirv_age_region_capabilities()[["openmp"]]
    },

    has_gpu_support = function(fake_gpu = FALSE) {
      if (fake_gpu) {
        FALSE
      } else {
        dust_cpu_seirv_age_region_capabilities()[["gpu"]]
      }
    },

    has_compare = function() {
      dust_cpu_seirv_age_region_capabilities()[["compare"]]
    },

    real_size = function() {
      dust_cpu_seirv_age_region_capabilities()[["real_size"]]
    },

    time_type = function() {
      dust_cpu_seirv_age_region_capabilities()[["time_type"]]
    },

    rng_algorithm = function() {
      dust_cpu_seirv_age_region_capabilities()[["rng_algorithm"]]
    },

    uses_gpu = function(fake_gpu = FALSE) {
      real_gpu <- private$gpu_config_$real_gpu
      !is.null(real_gpu) && (fake_gpu || real_gpu)
    },

    n_pars = function() {
      if (private$pars_multi_) length(private$pars_) else 0L
    },

    set_n_threads = function(n_threads) {
      prev <- private$n_threads_
      private$methods_$set_n_threads(private$ptr_, n_threads)
      private$n_threads_ <- n_threads
      invisible(prev)
    },

    set_data = function(data, shared = FALSE) {
      private$methods_$set_data(private$ptr_, data, shared)
    },

    compare_data = function() {
      private$methods_$compare_data(private$ptr_)
    },

    filter = function(time_end = NULL, save_trajectories = FALSE,
                      time_snapshot = NULL, min_log_likelihood = NULL) {
      private$methods_$filter(private$ptr_, time_end, save_trajectories,
                              time_snapshot, min_log_likelihood)
    },

    gpu_info = function() {
      ret <- dust_seirv_age_region_gpu_info()
      ret$devices <- as.data.frame(ret$devices, stringsAsFactors = FALSE)
      parent <- parent.env(environment())
      if (ret$has_cuda && exists("private", parent, inherits = FALSE)) {
        ret$config <- private$gpu_config_
      }
      ret
    }
  ))
class(seirv_age_region) <- c("dust_generator", class(seirv_age_region))
## Generated by odin.dust (version 0.3.13) - do not edit
seirv_age_region$set("public", "transform_variables", function(y) {
    info <- self$info()
    set_dim <- function(x, dimx) {
        if (length(dimx) > 1L) {
            dim(x) <- dimx
        }
        x
    }
    if (is.matrix(y)) {
        n <- ncol(y)
        Map(function(i, d) set_dim(y[i, , drop = FALSE], c(d,
            n)), info$index, info$dim)
    } else if (is.array(y)) {
        n <- dim(y)[2:3]
        Map(function(i, d) set_dim(y[i, , , drop = FALSE], c(d,
            n)), info$index, info$dim)
    } else {
        Map(function(i, d) set_dim(y[i], d), info$index, info$dim)
    }
})
